# src/reader2pdf/html.py
from __future__ import annotations

import time
from typing import Final
from .constants import MINIMAL_CSS

# Minimal HTML template for rendering articles
_HTML_HEAD: Final[str] = f"""<!DOCTYPE html>
<html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<style>{MINIMAL_CSS}</style>"""


def render_article_html(title: str, content_html: str, source_url: str) -> str:
    """
    Render the article content into a complete HTML document.
    """
    ts = time.strftime("%Y-%m-%d %H:%M:%S")
    return (
        f"{_HTML_HEAD}"
        f"<title>{title}</title>"
        f"<body>"
        f'<header>Source: <a href="{source_url}">{source_url}</a></header>'
        f"<h1>{title}</h1>"
        f"<article>{content_html}</article>"
        f"<footer><hr>Generated by reader2pdf at {ts}</footer>"
        f"</body></html>"
    )
